[config]

[templates.ghostty]
input_path = './templates_ansi/ghostty'
output_path = '~/.config/ghostty/config-colors'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.kitty]
input_path = './templates_ansi/kitty.conf'
output_path = '~/.config/kitty/kitty-colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.wezterm]
input_path = './templates_ansi/wezterm.lua'
output_path = '~/.config/wezterm/colors.lua'

[templates.eww]
input_path = './templates_ansi/eww.scss'
output_path = '~/.config/eww/colors.scss'
post_hook = '~/.config/eww/scripts/reload.sh'

[templates.foot]
input_path = './templates_ansi/foot.ini'
output_path = '~/.config/foot/colors.ini'
