[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/config-colors'

[templates.niri]
input_path = './templates/niri.kdl'
output_path = '~/.config/niri/niri-color.kdl'

