[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/config-colors'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.niri]
input_path = './templates/niri.kdl'
output_path = '~/.config/niri/niri-color.kdl'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/kitty-colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = './templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.wezterm]
input_path = './templates/wezterm.lua'
output_path = '~/.config/wezterm/colors.lua'
