[config]

# CREDIT: AvengeMedia/DankMaterialShell
# (qt theming)

[templates.qt5ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/qtct.conf'

[templates.qt6ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/qtct.conf'

[templates.kcolorscheme]
input_path = './templates/kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/CustomIdk.colors'
