[options]
master_path = "~/.config/dots"

[settings.master]
clipboardmanager = "clipvault"
isrofi = "true"
style = "custom"
theme = "dark"
waldir = "$HOME/.wallpaper/"
ewwbar_dir = "$HOME/.config/eww/bar/"
chsat_color = "true"

[settings.launcher]
launchertype = "vertical"
walsectype = "horizontal"
